import os
import json
from pathlib import Path
import sys

# Add root directory to sys.path so we can import from color_layout_analysis
root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
if root_dir not in sys.path:
    sys.path.append(root_dir)

from vision_pipeline import check_image_quality, extract_poster_text_and_coordinates
from build_dashboard import extract_chart_metrics_from_report, extract_cta_section_from_report, extract_ai_recommendations_from_report, calculate_cta_score_rubric, build_dashboard_html

def find_latest_image() -> str:
    """Finds the most recently modified image file in the ~/.hermes/ directory."""
    hermes_dir = Path.home() / ".hermes"
    with open("C:/Users/User/tools_debug.log", "a") as log:
        log.write(f"Searching in {hermes_dir}\n")
    if not hermes_dir.exists():
        with open("C:/Users/User/tools_debug.log", "a") as log:
            log.write("Hermes dir does not exist!\n")
        return None
    
    valid_exts = {'.jpg', '.jpeg', '.png', '.webp'}
    latest_file = None
    latest_time = 0
    
    for file_path in hermes_dir.rglob('*'):
        if file_path.is_file() and file_path.suffix.lower() in valid_exts:
            try:
                mtime = file_path.stat().st_mtime
                if mtime > latest_time:
                    latest_time = mtime
                    latest_file = file_path
            except OSError:
                continue
                
    with open("C:/Users/User/tools_debug.log", "a") as log:
        log.write(f"Found latest file: {latest_file}\n")
    return str(latest_file) if latest_file else None

def extract_visual_metrics() -> str:
    """
    Extracts text and visual metrics from the most recently uploaded poster image.
    Call this tool first when analyzing an image.
    
    Returns:
        str: A JSON string containing the extracted text, bounding boxes, blur score, and brightness score.
    """
    image_path = find_latest_image()
    if not image_path:
        return json.dumps({"error": "No image found in the ~/.hermes/ directory."})
        
    quality_ok, metrics = check_image_quality(image_path)
    if not quality_ok:
        return json.dumps({"error": metrics})
        
    laplacian_var, mean_brightness = metrics
    
    ocr_data = extract_poster_text_and_coordinates(image_path)
    if ocr_data.get("status") == "error":
        return json.dumps(ocr_data)
        
    payload = {
        "metadata": ocr_data["metadata"],
        "extracted_content": ocr_data["extracted_content"],
        "quality_metrics": {
            "blur_score": laplacian_var,
            "brightness_score": mean_brightness
        }
    }
    
    # Save a local copy just in case it's needed for debugging
    with open("vision.json", "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)
        
    return json.dumps(payload, indent=2)


def generate_html_dashboard(markdown_report: str, json_metrics: str) -> str:
    """
    Generates a beautiful HTML dashboard based on the visual metrics and the AI's markdown report.
    Call this tool after you have generated the full Markdown report.
    
    Args:
        markdown_report (str): The strictly formatted markdown report generated by the AI.
        json_metrics (str): The JSON string returned by the extract_visual_metrics tool.
        
    Returns:
        str: A success message containing the absolute path to the generated dashboard.html file.
    """
    try:
        ocr_result = json.loads(json_metrics)
    except Exception as e:
        return f"Error parsing JSON metrics: {e}"

    image_path = find_latest_image()

    # Extract metrics for dashboard
    headline          = ocr_result.get('extracted_content', {}).get('headline', '')
    total_text_blocks = ocr_result.get('metadata', {}).get('total_text_regions_found', 0)
    cursive_flag      = ocr_result.get('metadata', {}).get('cursive_font_warning_flag', False)
    ctas_list         = ocr_result.get('extracted_content', {}).get('detected_call_to_actions', [])
    typos_list        = ocr_result.get('extracted_content', {}).get('typos_found', [])
    raw_text_stream   = ocr_result.get('extracted_content', {}).get('raw_text_stream', [])
    
    blur_score        = ocr_result.get('quality_metrics', {}).get('blur_score', 0)
    brightness_score  = ocr_result.get('quality_metrics', {}).get('brightness_score', 0)

    # Color analysis
    color_data = None
    try:
        if image_path and os.path.exists(image_path):
            from color_layout_analysis import compile_color_data
            _, color_data = compile_color_data(image_path, ocr_result, blur_score=blur_score, brightness=brightness_score)
    except Exception as e:
        print(f"Color analysis failed: {e}")

    report_metrics = extract_chart_metrics_from_report(markdown_report)
    
    def get_metric(metrics_dict, standard_key, fallback_val):
        if not metrics_dict: return fallback_val
        if standard_key in metrics_dict: return metrics_dict[standard_key]
        norm_std = standard_key.lower().replace('_', '')
        for k, v in metrics_dict.items():
            if k.lower().replace('_', '') == norm_std: return v
        return fallback_val

    readability_score = get_metric(report_metrics, 'Readability', 85 if not cursive_flag else 65)
    cta_strength_from_llm = get_metric(report_metrics, 'CTA_Strength', None)
    if cta_strength_from_llm is not None:
        cta_strength = int(cta_strength_from_llm * 10) if (isinstance(cta_strength_from_llm, (int, float)) and cta_strength_from_llm <= 10) else int(cta_strength_from_llm)
    else:
        cta_strength = calculate_cta_score_rubric(ctas_list, raw_text_stream, headline)
    
    visual_impact = get_metric(report_metrics, 'Visual_Impact', 80 if blur_score > 500 else 60)
    info_clarity  = get_metric(report_metrics, 'Information_Clarity', 75 if total_text_blocks < 15 else 55)

    cta_score_display = f"{int(cta_strength)}/100"
    cta_found_flag   = len(ctas_list) > 0
    cta_summary_text = extract_cta_section_from_report(markdown_report) or ('CTAs found.' if cta_found_flag else 'No CTAs detected.')
    ai_recommendations = extract_ai_recommendations_from_report(markdown_report)

    integrated_blueprint = {
        'campaign_strategy': 'Multi-Channel Structural Audit',
        'overall_grade':    'B' if total_text_blocks > 20 or not cta_found_flag else 'A-',
        'm1_blur_val':      round(blur_score, 1),
        'm1_brightness':    int(brightness_score),
        'm2_total_words':   total_text_blocks,
        'm2_typos':         len(typos_list),
        'm2_typos_list':    typos_list[:5],
        'm2_cursive_flag':  cursive_flag,
        'contrast_header':  8.1,
        'contrast_body':    3.2 if total_text_blocks > 18 else 5.4,
        'contrast_cta':     7.6 if cta_found_flag else 0.0,
        'cta_found':        cta_found_flag,
        'cta_texts':        [c['text'] for c in ctas_list],
        'cta_coords':       ctas_list[0]['coordinates_str'] if (cta_found_flag and len(ctas_list) > 0 and 'coordinates_str' in ctas_list[0]) else "None Detected",
        'cta_score':        cta_strength,
        'cta_score_display': cta_score_display,
        'cta_analysis': {
            'cta_found':     cta_found_flag,
            'score':         cta_strength,
            'details':       cta_summary_text,
            'detected_ctas': [c['text'] for c in ctas_list]
        },
        'ai_recommendations': ai_recommendations,
        'suggestions': [
            "Optimise text density: consolidate regions into a clear visual hierarchy" if total_text_blocks > 15 else "Maintain clean layout structure",
            "Enhance CTA visibility: use contrasting colours and bold fonts" if not cta_found_flag else "CTA placement is optimal — maintain current strategy",
            "Replace cursive fonts with geometric typography for mobile" if cursive_flag else "Font selection supports platform versatility"
        ],
        'suit_insta': 0.45 if total_text_blocks > 22 else 0.88,
        'suit_print': 0.85 if total_text_blocks > 20 else 0.50,
        'suit_web':   0.78,
        'chart_blueprint': json.dumps({
            'chart_type': 'radar',
            'metrics': {
                'Readability':         readability_score,
                'CTA_Strength':        cta_strength,
                'Visual_Impact':       visual_impact,
                'Information_Clarity': info_clarity
            }
        }, indent=2),
        'audit_report_markdown': markdown_report,
        'color_data': color_data if color_data else {}
    }

    # Generate Dashboard
    try:
        build_dashboard_html(integrated_blueprint, markdown_report, html_filename="dashboard.html")
    except Exception as e:
        return f"Error building HTML dashboard: {e}"
        
    dashboard_path = os.path.abspath("dashboard.html")
    return f"Dashboard successfully generated! Absolute path: {dashboard_path}"
